# API 응답 code 상수 (ApiCode enum). HTTP 상태·메시지 매핑은 docs/api-codes.md 참고.
from enum import Enum


class ApiCode(str, Enum):
    # --- 공통 ---
    OK = "OK"
    # --- Auth ---
    SIGNUP_SUCCESS = "SIGNUP_SUCCESS"
    LOGIN_SUCCESS = "LOGIN_SUCCESS"
    LOGOUT_SUCCESS = "LOGOUT_SUCCESS"
    AUTH_SUCCESS = "AUTH_SUCCESS"
    EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS"
    NICKNAME_ALREADY_EXISTS = "NICKNAME_ALREADY_EXISTS"
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    UNAUTHORIZED = "UNAUTHORIZED"
    TOKEN_EXPIRED = "TOKEN_EXPIRED"
    # --- Users ---
    USER_RETRIEVED = "USER_RETRIEVED"
    USER_UPDATED = "USER_UPDATED"
    PASSWORD_UPDATED = "PASSWORD_UPDATED"
    USER_NOT_FOUND = "USER_NOT_FOUND"
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
    # --- Posts ---
    POST_UPLOADED = "POST_UPLOADED"
    POST_RETRIEVED = "POST_RETRIEVED"
    POSTS_RETRIEVED = "POSTS_RETRIEVED"
    POST_UPDATED = "POST_UPDATED"
    POST_NOT_FOUND = "POST_NOT_FOUND"
    POST_FILE_LIMIT_EXCEEDED = "POST_FILE_LIMIT_EXCEEDED"
    LIKE_SUCCESS = "LIKE_SUCCESS"
    LIKE_DELETED = "LIKE_DELETED"
    LIKE_NOT_FOUND = "LIKE_NOT_FOUND"
    ALREADY_LIKED = "ALREADY_LIKED"
    CONFLICT = "CONFLICT"
    FORBIDDEN = "FORBIDDEN"
    # --- Comments ---
    COMMENT_UPLOADED = "COMMENT_UPLOADED"
    COMMENT_UPDATED = "COMMENT_UPDATED"
    COMMENTS_RETRIEVED = "COMMENTS_RETRIEVED"
    COMMENT_NOT_FOUND = "COMMENT_NOT_FOUND"
    INVALID_POSTID_FORMAT = "INVALID_POSTID_FORMAT"
    # --- 요청/검증 (공통·미디어 등) ---
    INVALID_REQUEST = "INVALID_REQUEST"
    INVALID_REQUEST_BODY = "INVALID_REQUEST_BODY"
    MISSING_REQUIRED_FIELD = "MISSING_REQUIRED_FIELD"
    INVALID_FILE_FORMAT = "INVALID_FILE_FORMAT"
    INVALID_FILE_TYPE = "INVALID_FILE_TYPE"
    IMAGE_NOT_FOUND = "IMAGE_NOT_FOUND"
    INVALID_IMAGE_FILE = "INVALID_IMAGE_FILE"
    FILE_SIZE_EXCEEDED = "FILE_SIZE_EXCEEDED"
    IMAGE_UPLOADED = "IMAGE_UPLOADED"
    SIGNUP_IMAGE_TOKEN_INVALID = "SIGNUP_IMAGE_TOKEN_INVALID"
    SIGNUP_IMAGE_TOKEN_ALREADY_USED = "SIGNUP_IMAGE_TOKEN_ALREADY_USED"
    # --- 전역/기타 ---
    NOT_FOUND = "NOT_FOUND"
    METHOD_NOT_ALLOWED = "METHOD_NOT_ALLOWED"
    UNPROCESSABLE_ENTITY = "UNPROCESSABLE_ENTITY"
    RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED"
    LOGIN_RATE_LIMIT_EXCEEDED = "LOGIN_RATE_LIMIT_EXCEEDED"
    CONSTRAINT_ERROR = "CONSTRAINT_ERROR"
    DB_ERROR = "DB_ERROR"
    HTTP_ERROR = "HTTP_ERROR"
