"""add_fk_indexes

Revision ID: b4929405b32f
Revises: reports_unique_blind
Create Date: 2026-03-10 12:57:06.515251

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b4929405b32f"
down_revision: str | None = "reports_unique_blind"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_comment_likes_comment_id"), table_name="comment_likes")
    op.drop_index(op.f("ix_comment_likes_user_id"), table_name="comment_likes")
    op.create_index(
        op.f("ix_dog_profiles_profile_image_id"), "dog_profiles", ["profile_image_id"], unique=False
    )
    op.drop_index(op.f("ix_images_signup_expires_at"), table_name="images")
    op.drop_constraint(op.f("uq_post_images_image_id"), "post_images", type_="unique")
    op.drop_index(op.f("ix_posts_deleted_at_id"), table_name="posts")
    op.create_index(op.f("ix_reports_reporter_id"), "reports", ["reporter_id"], unique=False)
    # uq_user_blocks_blocker_blocked: 이미 DB에 존재하므로 스킵 (중복 생성 방지)
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_nickname"), table_name="users")
    op.create_unique_constraint(None, "users", ["email"])
    op.create_unique_constraint(None, "users", ["nickname"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("users_email_key", "users", type_="unique")
    op.drop_constraint("users_nickname_key", "users", type_="unique")
    op.create_index(op.f("ix_users_nickname"), "users", ["nickname"], unique=True)
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    # uq_user_blocks_blocker_blocked drop 스킵 (upgrade에서 생성하지 않았음)
    op.drop_index(op.f("ix_reports_reporter_id"), table_name="reports")
    op.create_index(op.f("ix_posts_deleted_at_id"), "posts", ["deleted_at", "id"], unique=False)
    op.create_unique_constraint(
        op.f("uq_post_images_image_id"),
        "post_images",
        ["image_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f("ix_images_signup_expires_at"), "images", ["signup_expires_at"], unique=False
    )
    op.drop_index(op.f("ix_dog_profiles_profile_image_id"), table_name="dog_profiles")
    op.create_index(op.f("ix_comment_likes_user_id"), "comment_likes", ["user_id"], unique=False)
    op.create_index(
        op.f("ix_comment_likes_comment_id"), "comment_likes", ["comment_id"], unique=False
    )
    # ### end Alembic commands ###
