# redis.asyncio용 로컬 스텁. 업스트림 타입이 동기 Redis 기준이라 async 메서드를 명시.
from collections.abc import Awaitable
from typing import Any

class ConnectionPool:
    @classmethod
    def from_url(
        cls,
        url: str,
        *,
        max_connections: int = ...,
        decode_responses: bool = ...,
    ) -> ConnectionPool: ...

class Redis:
    def __init__(self, *, connection_pool: ConnectionPool) -> None: ...
    def ping(self) -> Awaitable[bool]: ...
    def aclose(self) -> Awaitable[None]: ...
    def sadd(self, key: str, value: Any) -> Awaitable[int]: ...
    def srem(self, key: str, value: Any) -> Awaitable[int]: ...
    def delete(self, *keys: str) -> Awaitable[int]: ...
    def expire(self, key: str, seconds: int) -> Awaitable[bool]: ...
    def sismember(self, key: str, value: Any) -> Awaitable[bool]: ...
    def eval(self, script: str, numkeys: int, *args: Any) -> Awaitable[Any]: ...
