# app/core/codes.py
"""API 응답 code 값 통일. 타입/오타 방지용 enum."""

from enum import Enum


class ApiCode(str, Enum):
    """성공·실패 응답의 code 필드 값. str 상속으로 JSON 직렬화 시 문자열로 나감."""

    # --- 공통 ---
    OK = "OK"

    # --- Auth ---
    SIGNUP_SUCCESS = "SIGNUP_SUCCESS"
    LOGIN_SUCCESS = "LOGIN_SUCCESS"
    LOGOUT_SUCCESS = "LOGOUT_SUCCESS"
    AUTH_SUCCESS = "AUTH_SUCCESS"
    EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS"
    NICKNAME_ALREADY_EXISTS = "NICKNAME_ALREADY_EXISTS"
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    EMAIL_NOT_FOUND = "EMAIL_NOT_FOUND"
    UNAUTHORIZED = "UNAUTHORIZED"

    # --- Users ---
    USER_RETRIEVED = "USER_RETRIEVED"
    USER_UPDATED = "USER_UPDATED"
    PASSWORD_UPDATED = "PASSWORD_UPDATED"
    USER_NOT_FOUND = "USER_NOT_FOUND"
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"

    # --- Posts ---
    POST_UPLOADED = "POST_UPLOADED"
    POST_RETRIEVED = "POST_RETRIEVED"
    POSTS_RETRIEVED = "POSTS_RETRIEVED"
    POST_UPDATED = "POST_UPDATED"
    POST_NOT_FOUND = "POST_NOT_FOUND"
    POST_FILE_LIMIT_EXCEEDED = "POST_FILE_LIMIT_EXCEEDED"
    POSTLIKE_UPLOADED = "POSTLIKE_UPLOADED"
    LIKE_DELETED = "LIKE_DELETED"
    LIKE_NOT_FOUND = "LIKE_NOT_FOUND"
    ALREADY_LIKED = "ALREADY_LIKED"
    CONFLICT = "CONFLICT"
    FORBIDDEN = "FORBIDDEN"

    # --- Comments ---
    COMMENT_UPLOADED = "COMMENT_UPLOADED"
    COMMENT_UPDATED = "COMMENT_UPDATED"
    COMMENTS_RETRIEVED = "COMMENTS_RETRIEVED"
    COMMENT_NOT_FOUND = "COMMENT_NOT_FOUND"
    INVALID_POSTID_FORMAT = "INVALID_POSTID_FORMAT"

    # --- 요청/검증 ---
    INVALID_REQUEST = "INVALID_REQUEST"
    INVALID_REQUEST_BODY = "INVALID_REQUEST_BODY"
    MISSING_REQUIRED_FIELD = "MISSING_REQUIRED_FIELD"
    INVALID_EMAIL_FORMAT = "INVALID_EMAIL_FORMAT"
    INVALID_PASSWORD_FORMAT = "INVALID_PASSWORD_FORMAT"
    INVALID_NICKNAME_FORMAT = "INVALID_NICKNAME_FORMAT"
    INVALID_PROFILEIMAGEURL = "INVALID_PROFILEIMAGEURL"
    INVALID_FILE_URL = "INVALID_FILE_URL"
    INVALID_FILE_TYPE = "INVALID_FILE_TYPE"
    IMAGE_NOT_FOUND = "IMAGE_NOT_FOUND"
    INVALID_IMAGE_FILE = "INVALID_IMAGE_FILE"
    FILE_SIZE_EXCEEDED = "FILE_SIZE_EXCEEDED"

    # --- 전역/기타 ---
    NOT_FOUND = "NOT_FOUND"
    METHOD_NOT_ALLOWED = "METHOD_NOT_ALLOWED"
    UNPROCESSABLE_ENTITY = "UNPROCESSABLE_ENTITY"
    RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED"
    LOGIN_RATE_LIMIT_EXCEEDED = "LOGIN_RATE_LIMIT_EXCEEDED"
    CONSTRAINT_ERROR = "CONSTRAINT_ERROR"
    DB_ERROR = "DB_ERROR"
    HTTP_ERROR = "HTTP_ERROR"
